In [1]:
import numpy as np

def diag_dom(A):
    for i in range(len(A)):
        if abs(A[i][i]) < sum(abs(A[i][j]) for j in range(len(A)) if j != i):
            return False
    return True

A = np.array([[4,1,1],
              [2,6,1],
              [1,1,7]])

print("Is the matrix diagonally dominant?", diag_dom(A))
print(A)

B = np.array([[3,1,1],
              [1,5,1],
              [1,1,4]])

print("Is the matrix diagonally dominant?", diag_dom(B))
print(B)

Is the matrix diagonally dominant? True
[[4 1 1]
 [2 6 1]
 [1 1 7]]
Is the matrix diagonally dominant? True
[[3 1 1]
 [1 5 1]
 [1 1 4]]
